language: rust

cache: cargo

git:
  depth: 1

os:
  - linux
  - osx
  - windows

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - name: "rustfmt"
      os: linux
      env: RUSTFMT=true
      rust: nightly

install: .ci/install.sh
script: .ci/script.sh
